# Generated by Django 4.2.7 on 2026-03-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_notifications_userprofile_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam_email_reports',
            name='email_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
