# Generated by Django 4.2.7 on 2026-03-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_spam_email_reports_email_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_analysis',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
