# Generated by Django 4.2.7 on 2026-03-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_image_analysis_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishing_reports',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
