# Generated by Django 4.2.7 on 2026-03-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_phishing_reports_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_analysis',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='phishing_reports',
            name='explanation',
        ),
    ]
